language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: OBqoX9G0WcSSp2pGu8LYB1MSBxBLlQdK8gE+jQ4AU/SjVocMiYLL0TybgA3Ei64voKogalbMCvHAGHTFCpWcW/Nde7Jq4+LcK6kl+/KdNVIq3QJFlgAZJG78h7KNyZM0hN1KvvjyiADoJNO+qRErPg3CxNcjwXHaVxjqZBV7HCIef5IKMHDhNJZHOImh3xloI04/vEMaAwPwide2966xMSCxkR4LvfJNvCRciRF3BWv2zV1BUIXsrPq7PjBE5ohV9I6AN5otcsX7zE93biRZ1+lIEN89bS9HtrYIC9y12GKkQ9o+3BQRb7XAaB3h6tI/eBnpUSWJNVMmAFQdhIcVuaZ3IsGKqeb9s1PNyfIJF+FYmJZtIiLH/eKLm97pPXeJ9h3YDdMW9AHHW1CstPRhrd/afxSQ4e1s2VAEfQewwlNwn0a0HgOQ6CSY5gxdSYgTYu4+vNxy7ooO9ETSExYmdkyo66AiQMA8Y/WEx88ZkEF54WYb5JQRjRO9VFuJyi2XAPd3GgdXCJ6PFrGojBK89/QlHYOWqEvY4wVji4Pkv8Bco3LwO497qqcjWS9evoR2zV4oYFaTkcANLmOwQ6g42Ws5lO+bYIpoWH+ZxC57sYMKTvBi86KjknOIwCG3f898sLD8Nc7Kg/AIs6ZZTWEIgwmTCSmpyl3V5Kal8WBVVHM=
  app: guarded-dawn-76753
  on:
    repo: gcaliene/ispentwhat-API
