language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: DUjez0V6sXICOOkeGsu6d6ieGv8syTOm5q2UMuyRDzjVU80TfjhwZKUKmgR/8QqAC2HEexbLfwNOtQnfj7RtdRhVf5cVNMqHjJbmmRJiwSOqJ/hSMtw2pMIXms9ziXsjy2c9V5OqIJKNhb5SEqxwQlZYZOv6L524qNVe/DhYIsAUoEDM1o2E/XdLGG4JRalkZBLCx2QaQS33XX8eGpeheqwoJYUokLi3Rkn3keF+p4WoVylzTGZj/1uxd7Bx9aGHChXR45szpcG6PVEoVYxpPvcJXv5eocbPub0XwKrCc7yWF/cf3jF0/a0IYfeUTuVVibXFXPt6dAlEJD4I2wqmrG30aSkebZsPnkK9vXRQXlHv92xX1QQq+Ydy7xMXIAVcq8QV3A24prleNj/0mNJRVKrbgVBi6/PhQ2cQ3lsRdx2wyu8dL6elpaqn/Z8Ab7RpKDXXEjFr0JNNHVJIxiXjQE0e5kgaxHxh9cOMi9PebF5skySBSwXbKlNbL2yDd4wRN0Zc+9HpZdY/6CjLHe5BvrzHuaYMXTKoDaMhIDLxLJNZp+0jQ6dxGfG4kdvpmWS4WUBNhH70Xart/vLMf4lPn4fkpFemun/XAMHTbnafZs+Th/sqZDW2qJdhckttnBN5Zm2cCa3nrJDCL5Tausg9NHaLiBCgI2lyRgnprPETp/w=
  app: guarded-dawn-76753
  on:
    repo: gcaliene/ispentwhat-API
