language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ttdUW/I9KLETxA7w85lVs2T34MnK6nywTATjKfVro6gHCAxVzKUjx9a+sFun2ESi3OX3WZpDUMPblMNCfnu7/TdrZjc+u3GmMzk3iHGpWunej6RD+T6AcAWErLNLLRbPeCjvgynxDr0LudS7YWcd8iVi9QLChbIg8OJM7iDN/1jEXPeewrSgjUSjT0dfipclBElIHdzUEC46k8Wmva9g8vQUV0gDxJ0+q1JEoKBwEMrGVH6VH1JHsYng8OXo2U8x3IsrIY7fuE1KlZ1NlifZ2tchCKrGwyrPqBG9UsYoJ0WletZDV1HYlt35vQM6ssEzO+SEEZWw7vGJk1+fozJ3O4RqLme9XiYd0Qpwk1k1KJXX1hLtQEhWeGGIenv/XamjdaBcXOqHRFzytoOdqMqsCceXpmPQg+RZUlC0D35WiNRKPiUjfhewZ9UoCrxxIC9fDvoncISYM0yyX/CLy9TxOrRuqSHZqwpoMD5jYXDg08wUWNIFjOWBMJcJoHh4ASFd8FWauLRMU2/KUmVfPyu6XN5l1ut2wG+IjYrJ1/gau10oiHJsrlNBUktjOQ2hVQ/LpMbrtUI+fKJ3fEFoNSuyMze5TGm9mA3iGr9bBVboYx2o+mrEp8/z0yVJ30sd9itQqHrsP8iWMTFnLLUfo0RrMYyKitZJycRMfGIo3B3g1qg=
  app: ispentwhat-API
  on:
    repo: gcaliene/ispentwhat-API
